---

- name: (import-data) Import roles, groups and service users
  shell: 'ldapadd {{ ldap_connection }} -f {{ workspace }}/{{ item.file }}'
  environment:
    bind_password: '{{ bind_password }}'
  with_items:
    - { file: context.ldif }
    - { file: nd_role_catalogue.ldif }
    - { file: nd_role_groups.ldif }
    - { file: service-users.ldif }

- name: (import-data) Import users
  when: import_users_ldif != ''
  shell: 'time ldapadd {{ ldap_connection }} -c -f {{ workspace }}/{{ import_users_ldif }} > /var/log/import_users.log 2>&1'
  register: import_users_from_backup
  failed_when: import_users_from_backup.rc not in [0,33,68]
  # Allowed return codes:
  # 0=SUCCESS
  # 33=ALIAS_PROBLEM (invalid role association which should be ignored)
  # 68=ENTRY_EXISTS (duplicate entries should be ignored)
  environment:
    bind_password: '{{ bind_password }}'
